# Generated by Django 5.1.6 on 2025-02-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacity')),
                ('teacher', models.CharField(max_length=100, verbose_name='Teacher')),
            ],
        ),
    ]
